<?php

/**
 * Implements hook_form_alter().
 */
function pokehome_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    // Check if the content type is 'testimonial'. Adjust this to match your content type machine name.
    if ($form_id == 'node_testimonials_form') {
        $user = \Drupal::currentUser();
        $capitalized_name = ucwords($user->getDisplayName());

        // autopopulate the current user's name.
        if (isset($form['field_trainer_name']['widget'][0]['value'])) {
            $form['field_trainer_name']['widget'][0]['value']['#default_value'] = $capitalized_name;
            $form['field_trainer_name']['widget'][0]['value']['#attributes']['disabled'] = 'disabled';
        } else {
            Drupal::logger('testimonial_autopopulate')->warning('field_trainer_name not found.');
        }
    }
}
